ALTER TABLE [TEAMS] DROP CONSTRAINT IF EXISTS [TEAMS_fk0]
GO
ALTER TABLE [PLAYERS_1] DROP CONSTRAINT IF EXISTS [PLAYERS_1_fk0]
GO
ALTER TABLE [PLAYERS_1] DROP CONSTRAINT IF EXISTS [PLAYERS_1_fk1] 
GO
ALTER TABLE [STADIUMS] DROP CONSTRAINT IF EXISTS [STADIUMS_fk0]
GO
ALTER TABLE [TOURNAMENT_TABLE]  DROP CONSTRAINT IF EXISTS [TOURNAMENT_TABLE_fk0]
GO
ALTER TABLE [MATCH] DROP CONSTRAINT IF EXISTS [MATCH_fk0]
GO
ALTER TABLE [MATCH] DROP CONSTRAINT IF EXISTS [MATCH_fk1]
GO
ALTER TABLE [MATCH] DROP CONSTRAINT IF EXISTS [MATCH_fk2]
GO
ALTER TABLE [TEAMS_SPONSORS] DROP CONSTRAINT IF EXISTS [TEAMS_SPONSORS_fk0]
GO
ALTER TABLE [TEAMS_SPONSORS] DROP CONSTRAINT IF EXISTS [TEAMS_SPONSORS_fk1]
GO


DROP TABLE IF EXISTS [TOURNAMENT_TABLE]
GO
DROP TABLE IF EXISTS [PLAYERS_1]
GO
DROP TABLE IF EXISTS [TEAMS_SPONSORS]
GO
DROP TABLE IF EXISTS [SPONSOR]
GO
DROP TABLE IF EXISTS [PLAYERS]
GO
DROP TABLE IF EXISTS [MATCH]
GO
DROP TABLE IF EXISTS [REFEREE]
GO
DROP TABLE IF EXISTS [STADIUMS]
GO
DROP TABLE IF EXISTS [TEAMS]
GO
DROP TABLE IF EXISTS [CITY]
GO

------------------------------------------------------------------------------

CREATE TABLE [TEAMS] (
	team_id int NOT NULL PRIMARY KEY IDENTITY (11, 1),
	name nvarchar (255) NOT NULL ,
	city_id int NOT NULL
)
GO
CREATE TABLE [PLAYERS_1] (
	player_id int NOT NULL,
	season varchar(4) NOT NULL,
	team_id int NOT NULL,
	position nvarchar (255) NOT NULL,
    PRIMARY KEY (player_id, season)
)
GO
CREATE TABLE [STADIUMS] (
	stadium_id int NOT NULL PRIMARY KEY IDENTITY (301,1),
	name nvarchar (255) NOT NULL,
	hometeam_id int NOT NULL,
	capacity int NOT NULL,
)
GO
CREATE TABLE [TOURNAMENT_TABLE] (
	season varchar(4) NOT NULL,
	place int NOT NULL,
	team_id int NOT NULL,
	win int NOT NULL,
	draw int NOT NULL,
	lose int NOT NULL,
	goal_difference int NOT NULL,
	points int NOT NULL,
	comment ntext,
	PRIMARY KEY (season, place)
)
GO
CREATE TABLE [MATCH] (
	match_id int NOT NULL PRIMARY KEY IDENTITY (1, 1),
	date_time datetime NOT NULL,
	hteam_id int NOT NULL,
	ateam_id int NOT NULL,
	hteam_score tinyint NOT NULL,
	ateam_score tinyint NOT NULL,
	ref_id int NOT NULL,
	yellow_card tinyint NOT NULL,
	red_card tinyint NOT NULL
)
GO
CREATE TABLE [CITY] (
	id int NOT NULL PRIMARY KEY IDENTITY (50, 1),
	name nvarchar (255) NOT NULL,
)
GO
CREATE TABLE [SPONSOR] (
	sponsor_id int NOT NULL PRIMARY KEY IDENTITY (1022, 1),
	sponsor nvarchar (255) NOT NULL
)
GO
CREATE TABLE [REFEREE] (
	ref_id int NOT NULL PRIMARY KEY IDENTITY (601, 1),
	[name] nvarchar (255) NOT NULL,
	surname nvarchar (255) NOT NULL,
)
GO
CREATE TABLE [TEAMS_SPONSORS] (
	season varchar(4) NOT NULL,
	team_id int NOT NULL,
	sponsor_id int NOT NULL,
	PRIMARY KEY (season, team_id)
)
GO
CREATE TABLE [PLAYERS] (
	player_id int NOT NULL PRIMARY KEY IDENTITY (3000, 1),
	[name] nvarchar (255) NOT NULL,
	surname nvarchar (255) NOT NULL,
	nationality nvarchar (255) NOT NULL,
	birth_date date NOT NULL,
)
GO

---------------------------------------------------------------

ALTER TABLE [TEAMS] ADD CONSTRAINT [TEAMS_fk0] FOREIGN KEY ([city_id]) REFERENCES [CITY]([id])
ON UPDATE CASCADE
GO


ALTER TABLE [PLAYERS_1] ADD CONSTRAINT [PLAYERS_1_fk0] FOREIGN KEY ([player_id]) REFERENCES [PLAYERS]([player_id])
ON UPDATE CASCADE
GO
ALTER TABLE [PLAYERS_1] ADD CONSTRAINT [PLAYERS_1_fk1] FOREIGN KEY ([team_id]) REFERENCES [TEAMS]([team_id])
ON UPDATE CASCADE
GO


ALTER TABLE [STADIUMS] ADD CONSTRAINT [STADIUMS_fk0] FOREIGN KEY ([hometeam_id]) REFERENCES [TEAMS]([team_id])
ON UPDATE CASCADE
GO


ALTER TABLE [TOURNAMENT_TABLE] ADD CONSTRAINT [TOURNAMENT_TABLE_fk0] FOREIGN KEY ([team_id]) REFERENCES [TEAMS]([team_id])
ON UPDATE CASCADE
GO


ALTER TABLE [MATCH] ADD CONSTRAINT [MATCH_fk0] FOREIGN KEY ([hteam_id]) REFERENCES [TEAMS]([team_id])
ON UPDATE CASCADE ON DELETE NO ACTION--тут выдает ошибку, не рекомендуется ссылать два столбца из одной таблицы на один первичный ключ
GO
ALTER TABLE [MATCH] ADD CONSTRAINT [MATCH_fk1] FOREIGN KEY ([ateam_id]) REFERENCES [TEAMS]([team_id])
 ON DELETE NO ACTION
GO
ALTER TABLE [MATCH] ADD CONSTRAINT [MATCH_fk2] FOREIGN KEY ([ref_id]) REFERENCES [REFEREE]([ref_id])
ON UPDATE CASCADE ON DELETE NO ACTION
GO


ALTER TABLE [TEAMS_SPONSORS] ADD CONSTRAINT [TEAMS_SPONSORS_fk0] FOREIGN KEY ([sponsor_id]) REFERENCES [SPONSOR]([sponsor_id])
ON UPDATE CASCADE
GO
ALTER TABLE [TEAMS_SPONSORS] ADD CONSTRAINT [TEAMS_SPONSORS_fk1] FOREIGN KEY ([team_id]) REFERENCES [TEAMS]([team_id])
ON UPDATE CASCADE
GO







